[2024-02-24T21:42:20.688-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-02-24T21:42:20.691-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-02-24T21:42:20.691-0600] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-24T21:42:20.695-0600] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl> on 2024-02-24 00:00:00+00:00
[2024-02-24T21:42:20.700-0600] {standard_task_runner.py:60} INFO - Started process 8756 to run task
[2024-02-24T21:42:20.703-0600] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'drivers_to_bq', 'run_etl', 'scheduled__2024-02-24T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/driversDag.py', '--cfg-path', '/var/folders/2c/plc265_s31s2djb7299kj1fh0000gn/T/tmptkglhj1h']
[2024-02-24T21:42:20.704-0600] {standard_task_runner.py:88} INFO - Job 5: Subtask run_etl
[2024-02-24T21:42:20.735-0600] {task_command.py:423} INFO - Running <TaskInstance: drivers_to_bq.run_etl scheduled__2024-02-24T00:00:00+00:00 [running]> on host vamsees-macbook-pro.local
[2024-02-24T21:42:20.764-0600] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='drivers_to_bq' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-24T00:00:00+00:00'
[2024-02-24T21:42:20.765-0600] {driversDag.py:26} INFO - getting drivers data
[2024-02-24T21:48:07.839-0600] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-02-24T21:48:07.845-0600] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 8756. PIDs of all processes in the group: [8756]
[2024-02-24T21:48:07.845-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 8756
[2024-02-24T21:49:07.851-0600] {process_utils.py:149} WARNING - process psutil.Process(pid=8756, name='Python', status='running', started='21:42:20') did not respond to SIGTERM. Trying SIGKILL
[2024-02-24T21:49:07.856-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 8756
[2024-02-24T21:49:07.860-0600] {process_utils.py:79} INFO - Process psutil.Process(pid=8756, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='21:42:20') (8756) terminated with exit code Negsignal.SIGKILL
[2024-02-24T21:49:07.861-0600] {standard_task_runner.py:175} ERROR - Job 5 was killed before it finished (likely due to running out of memory)
