[2024-02-24T19:50:14.629-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T01:50:03.323786+00:00 [queued]>
[2024-02-24T19:50:14.635-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T01:50:03.323786+00:00 [queued]>
[2024-02-24T19:50:14.635-0600] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-24T19:50:14.641-0600] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl> on 2024-02-25 01:50:03.323786+00:00
[2024-02-24T19:50:14.646-0600] {standard_task_runner.py:60} INFO - Started process 1957 to run task
[2024-02-24T19:50:14.650-0600] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'drivers_to_bq', 'run_etl', 'manual__2024-02-25T01:50:03.323786+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/driversDag2.py', '--cfg-path', '/var/folders/2c/plc265_s31s2djb7299kj1fh0000gn/T/tmp27g0nukh']
[2024-02-24T19:50:14.650-0600] {standard_task_runner.py:88} INFO - Job 3: Subtask run_etl
[2024-02-24T19:50:14.683-0600] {task_command.py:423} INFO - Running <TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T01:50:03.323786+00:00 [running]> on host vamsees-macbook-pro.local
[2024-02-24T19:50:14.709-0600] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='drivers_to_bq' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T01:50:03.323786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-25T01:50:03.323786+00:00'
[2024-02-24T19:50:14.710-0600] {driversDag2.py:29} INFO - getting drivers data
[2024-02-24T20:02:19.238-0600] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-02-24T20:02:19.244-0600] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 1957. PIDs of all processes in the group: [1957]
[2024-02-24T20:02:19.244-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 1957
[2024-02-24T20:03:19.258-0600] {process_utils.py:149} WARNING - process psutil.Process(pid=1957, name='Python', status='running', started='19:50:14') did not respond to SIGTERM. Trying SIGKILL
[2024-02-24T20:03:19.265-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 1957
[2024-02-24T20:03:19.273-0600] {process_utils.py:79} INFO - Process psutil.Process(pid=1957, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='19:50:14') (1957) terminated with exit code Negsignal.SIGKILL
[2024-02-24T20:03:19.274-0600] {standard_task_runner.py:175} ERROR - Job 3 was killed before it finished (likely due to running out of memory)
