[2024-02-24T16:21:44.694-0600] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: drivers_to_bq.run_etl scheduled__2024-02-23T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
